### PR TITLE
Add config flow to Raspberry pi GPIO

### PR DESCRIPTION
**Pull request by engrbm87**
## Breaking Changes
The Raspberry Pi GPIO integration migrated to configuration via the UI. Configuring Raspberry Pi GPIO via YAML configuration has been deprecated and will be removed in a future Home Assistant release.

Your existing YAML configuration is automatically imported on upgrade to this release; and thus can be safely removed from your YAML configuration after upgrading **(will be added in a separate PR)**

## Proposed Changes
- Add configuration flow for Raspberry Pi GPIO integration.
- Limit PR to only binary sensors

Configuring ports through the UI:
 - Add  `Raspberry Pi GPIO` from the integrations page. It will prompt to select a platform (currently only binary_sensor is included. Other platforms will be added in future PRs)
 - Select the port from the list of available ports
 - Port will be configured with default settings. Settings can be updated through options.

### CODE REVIEW

**Comment by thecode** [comment]
Hi @engrbm87 
Thanks for the PR, it is a pretty big PR and I am reviewing this by myself so it may take time.
A better way for handling and removing entities is to have a dedicated config entry per switch/cover/sensor (a dedicated HA device)
This way the user can add the integration multiple time and will have multiple devices under the integration.
It will also allow the user to manage adding/removing devices using HA implementation without the need for dedicated support in the integration.
The integration can still validate there is no existing device using the same ports when trying to add a new device. a simple way to do it is to set the device unique id to be generated from the port, this way HA will abort if it already exists, however any other method such as looping an internal list we hold is also acceptable.
This is an example from Shelly integration:
image

Would you consider evaluating such approach and modify this PR?

Another question, is it possible to reduce the scope of the PR? e.g. create a smaller PR with less functionality and add additional functionality in follow up PRs, this will help faster reviewing

Thanks.

**Comment by engrbm87** [comment]
Hello @thecode , thanks for your comments. I didn't consider separate config entries because I thought of the raspberry pi as 1 device. But your idea definitely made the code simpler. And this was we are defining a separate device representing the actual device connected to a port.
Have a look at the updated code and let me know your comments. I limited this PR to binary sensors as requested.

**Comment by thecode** [comment]
> Hello @thecode , thanks for your comments. I didn't consider separate config entries because I thought of the raspberry pi as 1 device. But your idea definitely made the code simpler. And this way we are defining a separate device representing the actual device connected to a port. Have a look at the updated code and let me know your comments. I limited this PR to binary sensors as requested.

This PR deletes the other platforms, is this intended?

**Comment by engrbm87** [comment]
I will add the other platforms once this PR is finalized. We can't keep the other platforms with the existing code as they won't work.

**Comment by thecode** [comment]
> I will add the other platforms once this PR is finalized. We can't keep the other platforms with the existing code as they won't work.

In this case I can change the target branch to a working branch and once we finish all all platforms we can merge it to the main branch, but please keep the files as it will allow tracking changes in the next platforms PRs

**Comment by thecode** [comment]
I have tested this PR and the code also confirms it, there is no migration of the existing sensors to the UI, this is not good for user experience as it means existing users will loose their sensors and will need to recreate them.

Other notes:
I think it would be good to ask for a sensor name when adding a sensor and name the device with the supplied name so that the UI will show the names:
image

or the entity name it would be good to prefix with `gpio` so instead of `binary_sensor.23` it would be `binary_sensor.gpio_23`

**Comment by engrbm87** [comment]
Thanks for the feedback. I clearly mentioned in the PR description that importing will be added once the new code is approved. As the importing needs to take into consideration all platforms (sensor, switch and cover). Also there is the part related to legacy yaml config and new one. If this PR is ok I can proceed with adding the other platforms and then I can add the importing at the end.
As for the naming sure I can add the name key and use it for naming the device.

**Comment by engrbm87** [comment]
Can you please confirm if the base code is OK in order to add the other platforms?

**Comment by thecode** [comment]
> Can you please confirm if the base code is OK in order to add the other platforms?

base code is OK.
Since we now work on a branch (please take this in mind for next PRs they should start from `thecode/config-flow` branch and not the `main` branch.) I am fine with leaving the import and consider adding name as a last step (we can also discuss before how we do it).

**1 things should be addressed in this PR:**
Use a better entity_id -> e.g. `binary_sensor.gpio_23`, we can also just update the description to be `GPIO 23` instead of just 23 which will also update the created entity id.

**Review by thecode — APPROVED** [review]
Looks great, Thanks!

**Pull request merged**
