### PR TITLE
Add the option to have persistent switches

### PR DESCRIPTION
**Pull request by tomer-w**
Add new GPIO switch class - PersistentRPiGPIOSwitch which will restore the switch state after Home Assistant restart.
As part of the change move the core switch to use async functions.

### CODE REVIEW

**Comment by thecode** [comment]
Please update the readme  [README](https://github.com/thecode/ha-rpi_gpio/blob/main/README.md#switch) & the [info](https://github.com/thecode/ha-rpi_gpio/blob/main/info.md#switch)
- A new line to the table that explains the `persistent` key
- Update the full example

**Comment by tomer-w** [comment]
Done. Sorry for not doing it as part of the original commit.

**Comment by thecode** [comment]
> Done. Sorry for not doing it as part of the original commit.

No worries, there is one more place to update - [info](https://github.com/thecode/ha-rpi_gpio/blob/main/info.md#switch) (this is identical to the readme, just shown in a different place)

**Comment by tomer-w** [comment]
Done.

**Review by thecode — APPROVED** [review]
Thanks @tomer-w 👍

**Pull request merged**
