### PR TITLE
Port to use libgpiod instead of the RPi-specific libs

### PR DESCRIPTION
**Pull request by raboof**
Lightly tested. Edge detection not yet implemented.

Already using it in my Home Assistant deployment ;) https://codeberg.org/raboof/homeassistant-sbc/commit/597e37e57154ece76bcbb41b00b0b5f354af90a2

Refs #210

### CODE REVIEW

**Comment by raboof** [comment]
Still relevant.

I guess maybe someone should fork this project as `ha-gpio`? I don't really have the energy right now though.

**Comment by raboof** [comment]
:wave:

**Comment by aguedob** [comment]
Great work @raboof. Almost working fine for me. The only thing is that ports are in an inconsistent state after rebooting HA (reports state off, but are on). Any idea why? Could be related to the release of the lines? It seems it is not working

```  2023-12-17 18:27:56.794 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rpi_gpio/__init__.py", line 36, in cleanup_gpio
    gpiod_lines.close()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'LineRequest' object has no attribute 'close'```

**Comment by raboof** [comment]
> Great work @raboof. Almost working fine for me. The only thing is that ports are in an inconsistent state after rebooting HA (reports state off, but are on). Any idea why? Could be related to the release of the lines? It seems it is not working
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/rpi_gpio/__init__.py", line 36, in cleanup_gpio
>     gpiod_lines.close()
>     ^^^^^^^^^^^^^^^^^
> AttributeError: 'LineRequest' object has no attribute 'close'
> ```

Oops, that's very possible. I don't expect to have much time to look into this in the next weeks, but if you can come up with and verify a fix I'm happy to incorporate it.

> Another comment. For Raspberry Pi 5 I had to switch to gpiochip4
> 
> ```
> gpiochip0 [gpio-brcmstb@107d508500] (32 lines)
> gpiochip1 [gpio-brcmstb@107d508520] (4 lines)
> gpiochip2 [gpio-brcmstb@107d517c00] (17 lines)
> gpiochip3 [gpio-brcmstb@107d517c20] (6 lines)
> gpiochip4 [pinctrl-rp1] (54 lines)
> ```

Aha. I guess we want to make it configurable anyway. Would there be a nice way to auto-detect a sensible default (i.e. that picks gpiochip0 for rpi3 and gpiochip4 for rpi5)?

**Comment by aguedob** [comment]
> Aha. I guess we want to make it configurable anyway. Would there be a nice way to auto-detect a sensible default (i.e. that picks gpiochip0 for rpi3 and gpiochip4 for rpi5)?

I have a pi3 and a pi5. Once I have time I will have a look to it.

One more thing. I need to do a minor change also for the setup of the ports. Im using inverted logic for some of them and were not properly initialised. Not sure if this is fine for all cases. 
[https://github.com/raboof/ha-rpi_gpio/compare/port-to-libgpiod...aguedob:ha-rpi_gpio:port-to-libgpiod](url)

**Comment by stevaedrum** [comment]
Hi all,

Great job for the integration of new gpiod for Home Assistant.
Thanks @raboof for the updates.

I have tested, it's working weel, but how add edge detection ?
I can't find a correct documentation of the lib.

Thanks in advance for your answer and support.

**Comment by raboof** [comment]
> I have tested, it's working well

Good to hear!

> but how add edge detection ? I can't find a correct documentation of the lib.

I haven't looked into edge detection as I don't use that yet myself. Indeed the docs can be a bit hard to find and spotty. Indeed the [Python README](https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/tree/bindings/python/README.md) doesn't seem to have any documentation on reading, but there are some 'watch' [examples](https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/tree/bindings/python/examples), maybe those help?

**Comment by stevaedrum** [comment]
> > I have tested, it's working well
> 
> Good to hear!
> 
> > but how add edge detection ? I can't find a correct documentation of the lib.
> 
> I haven't looked into edge detection as I don't use that yet myself. Indeed the docs can be a bit hard to find and incomplete - the [Python README](https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/tree/bindings/python/README.md) doesn't seem to have any documentation on reading, but there are some 'watch' [examples](https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/tree/bindings/python/examples), maybe those help?

Thanks for your answer. I have find the same documentation of the API ;)
I have made some update, I can now get the change of the input in live, but it's quick and dirty.
I propose to commit it, quickly.

I wish you an happy new year and the health.

**Comment by raboof** [comment]
Given upstream hasn't participated in this thread yet, I wonder if we should fork this into a separate `ha-gpio` module (and rename some stuff)? Would you be willing to help maintain that @aguedob @stevaedrum?

**Comment by aguedob** [comment]
> Given upstream hasn't participated in this thread yet, I wonder if we should fork this into a separate `ha-gpio` module (and rename some stuff)? Would you be willing to help maintain that @aguedob @stevaedrum?

Same here

**Comment by raboof** [comment]
I did a bunch of renames and am now running https://codeberg.org/raboof/ha-gpio on my pi - seems to work fine! I'll stop providing updates here now, see you on the other side ;)

**Pull request closed without merging**
